# Set the prefix to ^T.
#unbind Cb
set-option -g prefix C-t
bind-key t send-prefix
#bind-key C-t last-window-

# 新規のWindowやPainをカレントディレクトリで開く
bind c new-window -c '#{pane_current_path}'

set-window-option -g mode-keys vi

# コピーした際にWindowsのクリップボードにも転送する (yum install -y xsel)
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xsel -bi"

# #H => マシン名
# #P => ペイン番号
# 最左に表示
set-option -g status-left '#H:[#P]'

# ステータスバーを１秒毎に描画し直す
set-option -g status-interval 1

#PCのステータスバーの追加
set-option -g status-right '#(wifi) #(battery --tmux) [%Y-%m-%d(%a) %H:%M]'

#256 color terminal
set -g default-terminal "tmux-256color"
set -g mouse on

# 設定ファイルをリロードする
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# | でペインを縦に分割する
bind | split-window -h

# - でペインを横に分割する
bind - split-window -v

# vimのキーバインドでペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Vimのキーバインドでペインを移動する
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+


bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# Windowの戻る進むのキーバインド
bind B previous-window
bind N next-window
bind L choose-window

# Split window with pane current path
bind %   split-window -hc "#{pane_current_path}"
bind '"' split-window -vc "#{pane_current_path}"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'  # prefix + shift + pでログ取得
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

# バッファ行数
set -g history-limit 100000

set-option -g default-shell "/usr/bin/fish"

# 一括でペインを閉じる
bind C-q kill-session

# 非アクティブな窓ガラス
set -g window-style 'fg=colour244,bg=colour234'

# アクティブな窓ガラス
set -g window-active-style 'fg=white,bg=black'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
